### PR TITLE
Added Emote Spin Option

### PR DESCRIPTION
**Pull request by lDiverse**
It is known that we have [emote]Spin as an option for certain emotes. For example: "KappaSpin" - although I feel personally that it is slightly redundant to be using extra images and such when it is a lot simpler to just add it in code...

With CSS animations/transitions and an extra 'spin' class. Emotes now spin when you do [emote]Spin. This works on all emotes whether they're channel/global or twitch ones.

### CODE REVIEW

**Comment by lDiverse** [comment]
Any specific reason? Or you just don't like it?

**Comment by MrAdder** [comment]
We do not want all emotes spinning hence the reason just for the specific
ones that do

On 22 March 2015 at 13:40, James Sherlock <notifications@github.com> wrote:

> Any specific reason? Or you just don't like it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrAdder/BeamExtended/pull/3#issuecomment-84610073>.
>



-- 
This email and any files transmitted with it are confidential and contain
privileged or copyright information. It is intended solely for the
individual(s) to whom it is addressed. You must not present this message to
another party without gaining permission from the sender. If you are not
the intended recipient you must not copy, distribute or use this email or
the information contained in it for any purpose other than to notify us.

If you have received this message in error, please notify the sender
immediately, and delete this email from your system. We do not guarantee
that this material is free from viruses or any other defects although due
care has been taken to minimise the risk.

**Comment by lDiverse** [comment]
Okay, maybe if I alter it to use a whitelist array? Therefore adding/removing spinning emotes is easier, and we save space by not having to store multiple versions of the same emote (being a spinning variation and a non spinning alternative)

**Comment by MrAdder** [comment]
Will consider that


On 22 March 2015 at 13:53, James Sherlock <notifications@github.com> wrote:

> Okay, maybe if I alter it to use a whitelist array? Therefore
> adding/removing spinning emotes is easier, and we save space by not having
> to store multiple versions of the same emote (being a spinning variation
> and a non spinning alternative)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrAdder/BeamExtended/pull/3#issuecomment-84610942>.
>



-- 
This email and any files transmitted with it are confidential and contain
privileged or copyright information. It is intended solely for the
individual(s) to whom it is addressed. You must not present this message to
another party without gaining permission from the sender. If you are not
the intended recipient you must not copy, distribute or use this email or
the information contained in it for any purpose other than to notify us.

If you have received this message in error, please notify the sender
immediately, and delete this email from your system. We do not guarantee
that this material is free from viruses or any other defects although due
care has been taken to minimise the risk.

**Pull request closed without merging**
